### PR TITLE
Rochester draft name in dropdown

### PR DESCRIPTION
**Pull request by tooomm**
Use correct naming label to stress what game type/category it is.

`Rochester Draft`

### CODE REVIEW

**Comment by Senryoku** [comment]
Buttons in the dropdown aren't correctly aligned when the text is too long. I took the easy route by removing "Draft", but I agree this need a proper fix.

**Comment by tooomm** [comment]
I guessed something like that already...

<br>

Is there the possibility to have groups in the dropdown? That would give clarity about the type/group the mode is about and has shorter names.

- Draft
   - <kbd>Rochester</kbd>
   - <kbd>Grid</kbd>
   - <kbd>Winston</kbd>
- Sealed
   - <kbd>Sealed</kbd>
- Other
   - <kbd>Jumpstart</kbd>

(Or maybe combine Sealed and Jumpstart in the same group)

Found this: https://stackoverflow.com/questions/43812817/how-to-set-optgroup-select-label-in-vue-js

**Comment by Senryoku** [comment]
I was thinking about doing this to separate two-players modes from all the others, but this is good too. Something like this?
image

**Comment by tooomm** [comment]
That looks very good!

Two litte things:
Maybe you want to order the draft types in alphabetical order?
Is it possible to have a small gap between the lowest draft option button and the sealed category headline below?

**Comment by Senryoku** [comment]
I'd rather keep the 2 players modes together. Added a small margin to better distinguish the categories.
I guess I can close this pull request :)

**Comment by tooomm** [comment]
That should do the trick 👍

**Pull request closed without merging**
