### PR TITLE
Normalize after color balancing

### PR DESCRIPTION
**Pull request by wrmacrae**
#139

### CODE REVIEW

**Review by Senryoku — COMMENTED** [review]
Math looks good to me. I think I see multiple issues with the implementation, I'll have to test it locally.

**Comment by Senryoku** [comment]
Pushed a working implementation and a small refactor.
Did some very limited testing, as expected this should help mostly with heavily multicoloured set (Ravnica).

**Comment by wrmacrae** [comment]
This looks great to me. I think I can try to write a test that makes 10000 colorbalanced boosters and validates that the number of some artifact's appearances is similar to the number of some other card's. And I can also run the test with the old code to validate the testing approach. As we get more special collations like walkers and MDFCs in booster generation I imagine we'll keep needing to normalize card frequencies in interesting ways, so hopefully we can reuse that testing logic (for example, we can also check that uncommon MDFCs and uncommon non-DFCs appear at the same rate in ZNR boosters).

**Comment by Senryoku** [comment]
Having a way to validate these changes would indeed be great!

**Comment by wrmacrae** [comment]
Alright! Added a test in the latest commit, which checks that the number of Cliffhaven Kitesails in 1000 ZNR packs is within 40% of the number of Murasa Brutes. Shouldn't be that flaky - I think the largest difference I saw was 12% (wrt average). Meanwhile I cherry-picked the test commit back to master and ran it and saw differences of ~60%. Will file a separate issue to track more tests like this, plus potentially factoring out the logic better and adding a group of "slow tests" that don't run every time for probabilistic things.

**Comment by Senryoku** [comment]
Perfect, thank you!
I agree for both more tests like this and separating them from standard tests.

**Pull request merged**
