### PR TITLE
Add a sample hand generator

### PR DESCRIPTION
**Pull request by aritsune**
Simple frontend-only change that adds a sample hand generator to the final card pool view. It lets you draw hands of 7 or keep drawing, inspired by the [sample hand generator from griselbrand.com](https://griselbrand.com/sample-hand/).

Only thing I'm not sure about here is the auto-basic land handling. It doesn't seem like the clientside has access to the full card db (understandably), so I compromised by just hardcoding some random JMP lands from the MTGA card database that we do have access to. It'd be nice to be able to respect the user's land set preferences, but all the ways to do it seem like overkill.

Also, the position for the button to open this might not be optimal.

### CODE REVIEW

**Comment by Senryoku** [comment]
Hi, thanks for your contribution!

Interesting idea. There's a few things I'd like to change in the implementation, is that OK with you if I work directly on this branch?
Specifically, I'd like to rewrite the component to use the script setup syntax, as Vue seems to be going in this direction and this is the default I use for all new components. Also the `MTGACards` import is very heavy (it's basically the DB of all cards available on Arena) and sadly tree shaking doesn't work there, so I'd rather avoid using it here, even if this means hard coding the basic lands (maybe we'll have to host the card images to be safe, idk).
Finally the space in the card pool controls is very limited, especially on smaller screens, what do you think about using an icon instead of `Get Sample Hand`? FontAwesome has this one https://fontawesome.com/icons/hand?f=classic&s=solid, but I could try to come up with something better. Maybe a hand holding a grid of cards?

**Comment by aritsune** [comment]
I think I can take care of those requests. Had a feeling even that JSON import was a bit much...

If it's okay to include an extra SVG file [this icon](https://pictogrammers.com/library/mdi/icon/cards/) from MDI seems like a good candidate.

**Comment by aritsune** [comment]
Converted the component to composition API, fixed some type checking errors, and hardcoded basic lands from J22 into a json file to use here

**Comment by Senryoku** [comment]
Thanks for the changes!
I went ahead and modified it to better match the rest of the code base. I also changed it to use the icon you proposed (I spent some time trying to make something myself but uh, yeah, still not a designer :D).
A far as I'm concerned it's ready for merging, is there anything else you want to add?

**Comment by aritsune** [comment]
Nope, nothing to add, thanks for the help!

**Pull request merged**
