### PR TITLE
Add Team Draft option

### PR DESCRIPTION
**Pull request by wrmacrae**
Bolded sections could use input, but everything is functional now and we can merge it as soon as folks are happy with the look.

Addressing issue #97 by adding a team draft option.
- Draft-specific setting, currently the first Draft Specific Option (with the reasoning that this is a setting used in pro magic, whereas booster modifications and burned card are variants that don't see organized play). **Open to opinions about whether it should go lower in the options.** 
Screen Shot 2020-09-08 at 9 48 49 PM

- Setting Team Draft disables the maximum players setting and locks it into 6. Unsetting it sets maximum players to the default of 8 and undisables.

Screen Shot 2020-09-07 at 11 28 19 AM

- Show teams in seating order using colors (dark green / dark blue, because red is used by icons; #103810 and #101038). I'm colorblind, so **feedback/changes to these colors appreciated**! 

Screen Shot 2020-09-07 at 4 01 06 PM

- Change bracket generation when team drafting. Using the same colors as the seating order, and some visual changes to allow for space around the green/blue sections. Winners get a bigger box-shadow and a lighter color, to hopefully indicate teams and winners clearly. **Would appreciate feedback on how this looks, too!**
Screen Shot 2020-09-08 at 9 35 48 PM

### CODE REVIEW

**Comment by Senryoku** [comment]
Thanks for your work! Some notes:
* You can switch to Team Draft with more than 6 players in the session, we should disable the option or display an error when the user tries to activate it (probably better).
* Similarly bots do not contribute to the player count for the Maximum Players checks and let you have more than 6 drafters.
* I'd choose more subdued colors like #2f3257 & #573535 or #2f3257 & #2b523b if this is still readable. We could try an slim white outline on the icons to have more freedom.
image
image
(I picked these examples really quickly, I'll spend more time on it if you think these are viable)
We could also try to be more subtle, for example with a gradient:
image 
* During the draft the code path for player display is different so the team colors aren't displayed, I guess we should have them here too.
* If possible use the same css classes (.teama .teamb) in the bracket rather than redeclare them.

**Comment by wrmacrae** [comment]
Thanks for all the feedback! I'll be working through these things gradually. I just did another pass at colors based on your suggestion but with a modification to the brightness. With #2f3257 & #2b523b I have trouble picking out the white text from the background color (my vision is pretty poor, even corrected!), but I really like that those colors are less saturated than the ones I had originally. The grey background we had already was 16% brightness, and those colors are 34%, so I split the difference, and brought them down to 25% -- still brighter than the grey, but a little darker so that I can see the white text. Same hue and saturation as you suggested. I think it could even be a little less bright, but I don't feel strongly about that. There's some more nuance to comparing these colors to grey using HSL vs HSV, but hopefully the current image just strikes a good visual balance of "colors not too stark," "can tell teams apart," and "can read icons and text."
Screen Shot 2020-09-09 at 8 27 29 AM

Also, I like the idea of reducing the duplication of these colors into multiple css files (it actually tripped me up just now, so that's bad!), so I will investigate alternatives, although it's a bit tricky because I need this to override the `bracket-winner`, `bracket-player`, and `.player-list li` background values (or to add some complexity that doesn't apply the classes with those backgrounds), and because I needed to change more than just the background to make the brackets look okay and the winners legible in the bracket. Will try some stuff and follow up on this next!

**Comment by Senryoku** [comment]
I see, I wondered why you specified .player-list for the team backgrounds, make sense now.
As a band-aid solution I'd declare them like this: 
```
.teama,
.player-list > .teama {
	background: #21402e;
}
.teamb,
.player-list > .teamb {
	background: #222440;
}
```
And remove the declaration from Bracket. 
I wonder if we should remove the background change for bracket-winner and just use a box-shadow/border, I feel like making the background lighter for the winning team doesn't really work and removing it entirely "solves" our priority problem :)

**Comment by wrmacrae** [comment]
Things to fix:
- [ ] Color saturation
- [ ] CSS repetition
- [ ] Use team colors during draft
- [ ] Winner indication in brackets
- [ ] Bracket generation buttons based on current settings instead of current bracket
- [ ] Error message when starting team draft with wrong drafter count (including bots, you can already decrease max players below the current number of players or add too many bots, so I think we just need to explain to the owner before they can start the draft and leave it to them to change modes or kick players.
- [ ] setBoostersPerPlayer fix

**Comment by wrmacrae** [comment]
Here's a new pass at the bracket winner styles. I changed the non-team one, too, so that it uses the outline and bolds the text but doesn't change the background. I think it's relatively easy to make non-team brackets have the old look if we prefer that, but I was thinking this might be more consistent and also a little cleaner to read overall even winner style aside.
Screen Shot 2020-09-10 at 9 52 36 PM

Screen Shot 2020-09-10 at 9 48 57 PM
Screen Shot 2020-09-10 at 9 48 32 PM

**Comment by Senryoku** [comment]
Fixing setBoostersPerPlayer is just a matter of broadcasting boosterPerPlayer:
```
			this.forUsers(u =>
				Connections[u].socket.emit("sessionOptions", {
					boostersPerPlayer: this.boostersPerPlayer,
					customBoosters: this.customBoosters,
				})
			);
```
(Looks like GitHub has an option to allow maintainers to commit to PRs branches for this kind of quick fixes, if you want to enable it)

I'm all for a consistent look, background change for winner(s) wasn't a good idea to begin with anyway!

**Comment by wrmacrae** [comment]
I think I've got "Allow edits by maintainers" checked (although I didn't know about this, so it must have been a default thing, which is nice). Anyway, added the line to Session.js -- thanks for catching that, I saw loops that looked the same in server and session and actually missed the fact that they were sending different parts of the options (which is probably a good cautionary tale about how I shouldn't sneak random fixes/refactors into a large, unrelated PR).

**Comment by tooomm** [comment]
>(Looks like GitHub has an option to allow maintainers to commit to PRs branches for this kind of quick fixes, if you want to enable it)

Yeah, that should be enabled by default. You should have write access to the `feature/teamDraft` branch in his repo where the PR comes from: https://github.com/wrmacrae/MTGADraft/tree/feature/teamDraft

As part of a comment in the changed files or reviews you can suggest code changes which can be accepted super easy:
https://haacked.com/archive/2019/06/03/suggested-changes/

<br>

Awesome change btw! Looking forward to that @wrmacrae

**Comment by Senryoku** [comment]
I think we should disable bots for team drafting (i.e. allow draft launch only with 6 human players and set the session property bots to zero when activating team draft).
There is no way for users to correctly setup teams if bots are involved (their placement around the table isn't clear and subject to change) and team brackets doesn't make much sense with empty seats.

What do you think?
(I can merge the PR and make the change myself if that's better for you)

**Comment by wrmacrae** [comment]
Agreed, bots don't make much sense, and if you have a weird player count you can just do a normal draft with bots instead. In the future we could try supporting 4-player and 8-player team draft, but to keep things simple, I made it require exactly 6 players, and it provides an error message that explains that now. I think the one drawback would be that people can't "preview" how the team draft features work before the other players show up; I have the impression it's common for organizers who are new to the app or a feature to want to fire off a quick draft with bots to test things out, but I think the difference between normal draft and team draft is so narrow that this shouldn't really be a problem.

**Comment by wrmacrae** [comment]
Oh, and I'm aware that you could end up with >6 players in the draft before you switch to team draft, just like you can have > max players in your draft if you change the setting after inviting people. I think in that case we have to just message that to the owner and have them decide what they want to do, so the current performance is the best experience I can imagine for that situation.

**Comment by Senryoku** [comment]
Great! Looks good to me! Thanks for this last change and the whole feature :)

**Comment by tooomm** [comment]
Just watched your Team Draft implementation live @wrmacrae... on Twitch. Looked good. :)

Some observations:
- Log shows two players as `(empty)` instead hiding them out for Team Draft logs.
- There are no team colors shown in logs for Team Draft logs.
- I had the idea already... it would be awesome to see not only card pool and picks, but also the deck that gets exported which is most likely the deck the person ended up. Makes evaluation of picks and power level of decks way easier and compares better than all pool. Makes the color icons next to the player name also better if they are calculated

Never realized that there is a export to magicprotools option. That's cool!

**Comment by wrmacrae** [comment]
Thanks @tooomm - didn't realize Team Lords was practicing before the event next week! Agreed about the logs, I never looked at or thought about them in context. I'll open an issue for that. Regarding the third bullet, I agree about seeing what decks players ended up making in the app, it's one of the next major things I want to work on, and I've been tracking it here: https://github.com/Senryoku/MTGADraft/issues/115 . I'm having some difficulty figuring out all the right spots to add it to the UI (logs, bracket, player seating) in the cleanest way, so would appreciate thoughts over there.

**Comment by tooomm** [comment]
>Thanks @tooomm - didn't realize Team Lords was practicing before the event next week! 

Haha, yeah. That's cool... wasn't aware that there is a live Team Draft event happening with famous streamers. And they use the mtgadraft page and your fresh feature!:)
Do you know the schedule by chance?

Thanks for transferring the suggestions to #136!

Will have a look at #115.

**Comment by wrmacrae** [comment]
> > Thanks @tooomm - didn't realize Team Lords was practicing before the event next week!
> 
> Haha, yeah. That's cool... wasn't aware that there is a live Team Draft event happening with famous streamers. And they use the mtgadraft page and your fresh feature!:)
> Do you know the schedule by chance?
> 
> Thanks for transferring the suggestions to #136!
> 
> Will have a look at #115.

Ya, the event was a lot of the motivation for adding the feature. They started talk on podcasts and twitter a few weeks ago, and since I've really been hoping for it to be a team draft (https://twitter.com/wrmacrae/status/1301947396901842944). 6pm PDT Wednesday 9/30 for the real event https://twitter.com/ChannelFireball/status/1309170222453096449 - not 100% confirmed they will actually draft on this app, but seems to be the preference of Team Lords.

**Pull request merged**
