### PR TITLE
Track needed wildcards

### PR DESCRIPTION
**Pull request by Senryoku**
- [x] Combine Rare/Mythic WC count in header
 - [x] Display WC breakdown (main/side by rarity) in dropdown
 - [x] Retrieve WC balance from logs
 - [x] Display WC balance in dropdown

### CODE REVIEW

**Comment by tooomm** [comment]
First notes:

- Picked basic lands in ZNR are counted towards the wildcard count.
- If the option is disabled in collection statistics, the required wildcard count is still shown for your deck.
- When you put cards to the sideboard they are substracted from the count, even though Arena offers no option to only craft the main deck. Not even sure if you can play with decks that contain uncrafted cards in the sideboard.
This could be desired behavior in Bo1 games, but can lead to problems in Bo3 though.

Not sure yet if I prefer the individual display of each wildcard type next to each other as seen in your screen:

Or if a combined view with details on hover like in MTGA itself (e.g. tooltip or menu) is better in order to keep the UI cleaner.

**Comment by Senryoku** [comment]
This where I'm at:
image
Without hovering, it displays the combination of Rare and Mythic wildcards needed.
I've kept main deck and sideboard values separated (I guess sideboard cards won't be crafted most of the time: either because they're unplayable or because of the format (BO1)).
The result is pretty busy imho, any suggestion?

**Comment by tooomm** [comment]
> I guess sideboard cards won't be crafted most of the time: either because they're unplayable or because of the format (BO1)).

I'm still not sure if you can even play with a deck that contains any uncrafted cards in the sideboard...

Arena offers no option to only craft the main deck, you have to craft all cards in the deck AND sideboard, or you have to go trough all the cards in your deck manually to craft them and then delete some (Bo3) or all (Bo1) of them from your sideboard as well.

>Without hovering, it displays the combination of Rare and Mythic wildcards needed.
>The result is pretty busy imho, any suggestion?

I'm not a big fan of the combined icon as that feels difficult to see and understand as it is currently. We can think about that in detail later maybe.

The full count of available wildcards doesn't needed to be dispalyed IMO, in the end it's only relevant if you have enough left?
For example, the "needed" count could turn orange if it drops below 6 or 3 with the currently picked card as warning, and red if you don't have enough left. Probably the red part is already sufficient.

Thinking this further:
Ideally, the color indicator would show up in the pick area already before you make a pick. Actually that information would be more valuable and relevant than the current collection status there! I mean... if I have 1/4 or 3/4 copies of a card tells me not too much right away. Picking a certain card won't grow my collection unless the picked count supersedes the already owned number and I end up spending a wildcard on it because I want to play that many. It also doesn't tell me if I need to spend a wildcard in the first place without considering the quantity of those cards picked already. As a result the count is not that helpful on its own.
So my picking decisions are mostly not based off my collection count, but rather if I have to spend wildcards in order to play them - collection count is just an indirect hint to that. In Arena itself that might be interesting information as it tells me right away my collection is not full yet and picking that card will count towards it.
Sorry for turning your new system upside down. 😄

To wrap it up (my idea involved during writing as well haha):
- I suggest to remove the current collection count displayed in the drafting portion, but instead show a wildcard symbol there if the owned count and already picked count is even or lower. That way I even get the relevant information ahead while picking and not only after the damage is done.
Wildcard symbol means: If I pick this card I will have to spend a certain wildcard in order to play it.
- Don't display the total number of available wildcards and add color coding to the needed quantity instead to de-clutter the menu a bit

**Comment by Senryoku** [comment]
> I'm still not sure if you can even play with a deck that contains any uncrafted cards in the sideboard...

You can't, but anyone worried about their wildcards will take the time to remove these cards, I don't think that's a problem.

> I'm not a big fan of the combined icon as that feels difficult to see and understand as it is currently. We can think about that in detail later maybe.

Yeah, it's not clear. I opted for displaying rare and mythic WC needed for the main deck:
image
 
> The full count of available wildcards doesn't need to be dispalyed IMO, in the end it's only relevant if you have enough left?

True, but I think it can help for context and to make decision (it's easier to burn a WC when you have hundreds :)). I've added color coding anyway.

> I suggest to remove the current collection count displayed in the drafting portion, but instead show a wildcard symbol there if the owned count and already picked count is even or lower. That way I even get the relevant information ahead while picking and not only after the damage is done.
Wildcard symbol means: If I pick this card I will have to spend a certain wildcard in order to play it.

True, I like keeping the count for context, but I've reworked it a bit.
image
The color change and icon appear only if picking the card will exceed what's available in your collection.

**Comment by tooomm** [comment]
Sorry for getting back to this with delay...

<br>

>>I'm still not sure if you can even play with a deck that contains any uncrafted cards in the sideboard...
>
>You can't, but anyone worried about their wildcards will take the time to remove these cards, I don't think that's a problem.

Ok, good to know. Agreed. 👍 

<br>

>>The full count of available wildcards doesn't need to be dispalyed IMO, in the end it's only relevant if you have enough left?
>
>True, but I think it can help for context and to make decision (it's easier to burn a WC when you have hundreds :)).

I'm not sold on this yet. :)
As you stated already the menu is quite cluttered currently. Keeping such special information doesn't help in making it better. I still think the user would benefit more from a clear view in the vast majority of cases.
It would be a nice information to have for sure. Maybe as part of your collection stats?
That way a user can still easily double check with a single click - even during a draft - if they are that low on wildcards, care that much or a new set requires special wildcard management in the very beginning.
As a collection can easily be not 100% up to date, chances are the value is inaccurate anyway and it should be more of a guidance than a strict dependency. Users doesn't have this information at all currently.
What do you think?
<br>

>>I suggest to remove the current collection count displayed in the drafting portion, but instead show a wildcard symbol there if the owned count and already picked count is even or lower. That way I even get the relevant information ahead while picking and not only after the damage is done.
Wildcard symbol means: If I pick this card I will have to spend a certain wildcard in order to play it.
>
>True, I like keeping the count for context, but I've reworked it a bit.

Same here, the context of draft doesn't require that information in my opinion. It adds noise to the draft instead and takes focus from the way more important wildcard symbol once it shows up.
During a draft you don't care if you have already 2 or 3 copies of a card. In Both cases you don't need to spend a wildcard. Check. Same if you have a full collection of that card.
If you happen to pick a 3rd copy in the "I own 2 copies" example, you want to know that you need to spend a wildcard if you play the card. That's it, no?
Again, if you want to grow your collection or want to have a playset for Standard, you normally don't do picks based on that as you make your draft worse... you simply craft the cards on demand? Am I that wrong here? 🤔 

<br>

>The color change and icon appear only if picking the card will exceed what's available in your collection.

I like it.

Further improvements:
- The color change to yellow only happens in the new menu, not its headline. It's easy to miss that way.
- Red > Yellow?
- During pick selection, the user doesn't know if he has enough wildcards of that type spare. He only sees the wildcard symbol in the upper left card corner because he would need to spend one. When telling him after the pick that he can not play all of his great on-color rares, it's already too late. :)
The collection count could be a wildcard count there (needed vs total of that type), also with color coding. That would be a better and more relevant context there I think - you see, I'm not super high on collection count. 😄
Or a `not enough wildcards`/`low on wildcards` hint. Something like a crossed out wildcards symbol might also work great!

**Comment by Senryoku** [comment]
Yeah, you're right... I felt like keeping the count would help with understanding the feature, but it's probably just clutter.
Anyway:
 - Missing card with available wildcard
   image
 - Missing card without enough available wildcards
   image

I want to keep the total count of wildcards here also because it just seems like the obvious spot for it. Tweaked the style a bit to draw attention on the important part.
image

I choose yellow for the color change because it's easier to read on a dark background (I could search for a legible shade of red but... yeah, it was faster this way :p)

**Comment by Senryoku** [comment]
Merging this to deploy it and hopefully get some user feedback; Discussion can continue on the opened issue.

**Pull request merged**
