### PR TITLE
CardPopup: Card Oracle

### PR DESCRIPTION
**Pull request by Senryoku**
This PR adds an overlay activated by holding Alt to CardPopup, it displays Scryfall card data without relying on its image, and more specifically its oracle text.
 
 - [x] Buggy on Firefox. Primary card overlay never show up, probably a z-index problem.
 - [x] Better support for DFCs

### CODE REVIEW

**Comment by sprangg** [comment]
Looks and feels great to use! However, I was wondering, could the oracle text overlay also appear on a card when simply hovering mouse over it in the pack and holding alt? This would make it even handier to check during drafting simply with the flick of a button, no right mouse click needed.

The current right mouse click oracle text functionality could still be preserved though, in addition.

**Comment by Senryoku** [comment]
> Looks and feels great to use! However, I was wondering, could the oracle text overlay also appear on a card when simply hovering mouse over it in the pack and holding alt? This would make it even handier to check during drafting simply with the flick of a button, no right mouse click needed.
> 
> The current right mouse click oracle text functionality could still be preserved though, in addition.

Retrieving the oracle text requires an additional request to Scryfall, it was already done on right click (to retrieve related cards), so it was quite easy to integrate it to the zoom feature.
Changing the behavior would either mean to systematically send this request for each card in advance, which I wanted to avoid, or sending it on hover/alt press, which will probably feel sluggish most of the time.

**Comment by tooomm** [comment]
Sometimes the related cards overlay the clicked card on load for me:
Untitled

On the main page, this did not happen so far.

**Comment by sprangg** [comment]
> Changing the behavior would either mean to systematically send this request for each card in advance, which I wanted to avoid, or sending it on hover/alt press, which will probably feel sluggish most of the time.
I understand. Let's go with the current implementation then, it's certainly good enough. Thank you for your great work as always!

**Comment by tooomm** [comment]
>or sending it on hover/**alt press**, which will probably feel sluggish most of the time.

Do you expect a big delay in that case? No information about related cards needs to be requested here. And only the hovered card should be requested.

I actually like that as additional way to get oracle information right away. Often it's not needed to see the big card or wait for other related cards requests.

I can also see a setting to show oracle information always, or instead of downloading pictures altogether if you are on a slow or limited connections being useful.

**Comment by tooomm** [comment]
Another cool addition to the page! You found a good solution here. 👍
I think the loading times are ok for the Oracle texts.

I did not think about users holding alt while moving the mouse around, haha. 🙈 
It seems not too bad, but is sending a request only possible on button press? From a user point the experience should be fine and expected.

>However I rarely had reports of images not loading, people trying to use the app on really poor connections, or similar problems, so I'm not sure how relevant this feature would be in practice.

I do agree.

<br>

>Sometimes the related cards overlay the clicked card on load for me

I did not encounter this with the recent changes. But I noticed that related cards that display the card back placeholder until an image is loaded are placed above the clicked card still. Once the card picture is loaded, it jumps to the back.

<br>

Two other small issues (maybe it's needed to zoom in on the picture to better spot the second):
- Hover/small card: Card name and mana cost scale too much and are cut off
- Hover/small card: Overlay is a bit too short and doesn't cover all card at the bottom
- Well, and the single, white "check box" in the big, empty new section next to a card with no relations 😛 

header

**Comment by tooomm** [comment]
>This one is intended, for consistency. It doesn't look weird in my eyes, but maybe I'm alone on this one.
(I also think the tab looks better than having the card float without "anchor" when there's no related cards, and it lets me display the hint for the Alt shortcut)

The "anchor" itself is fine!
I don't perfectly like the white, glowing square representing the selected card in an empty "wheel" if there are no related cards. I think displaying it the same as a not selected card in the "wheel" would be better. As the wheel is not available for one card, it also fits concept wise to use the "non-active" grey.
Not showing single squares is also good, maybe even better.

**Pull request merged**
