### PR TITLE
add icons to dropdown and script to make icons

### PR DESCRIPTION
**Pull request by wrmacrae**
Using icons from https://andrewgioia.github.io/Keyrune/index.html
Added script to download svgs from there, remove color, and set uniform widths

### CODE REVIEW

**Comment by wrmacrae** [comment]
http://www.giphy.com/gifs/LPBQDnz5Q1dJeuWcJS

**Comment by wrmacrae** [comment]
Fixes https://github.com/Senryoku/MTGADraft/issues/9

**Comment by wrmacrae** [comment]
All of thee SVGs are auto-generated by client/public/img/sets/update-set-images.sh
Other changes are in client/public/index.html and client/public/css/style.css

**Comment by wrmacrae** [comment]
> http://www.giphy.com/gifs/LPBQDnz5Q1dJeuWcJS

Oops, not sure why giphy capture uploads private gifs!

combo-icons

**Comment by wrmacrae** [comment]
The previous svgs had varying dimensions, which made them not work well in the dropdown. But a problem with these uniformly 32x32 ones is that the M21 symbol is almost illegibly small. Maybe we want them uniform size like here but just a slightly-larger uniform size.

**Comment by wrmacrae** [comment]
It looks like the actual magic cards have a uniform symbol height and then some like the core sets just have a much wider (and therefore larger) set symbol. I can try to mimic that more to get a larger M21, and then just add spacing within the combobox so that the set names line up. The icon set I started with scales down the wider icons to keep a uniform square size, but I'll investigate ways to work with that.

**Comment by Senryoku** [comment]
> 
> 
> It looks like the actual magic cards have a uniform symbol height and then some like the core sets just have a much wider (and therefore larger) set symbol. I can try to mimic that more to get a larger M21, and then just add spacing within the combobox so that the set names line up. The icon set I started with scales down the wider icons to keep a uniform square size, but I'll investigate ways to work with that.

Sounds good!
I'd also like to port your bash script to python to add it to ManageCardData.py and keep everything in one place (I am currently pulling icons from Scryfall at the end of this script).

**Pull request closed without merging**
