### PR TITLE
Card Popup (replace card zoom)

### PR DESCRIPTION
**Pull request by Senryoku**
Switched card zoom to card popup, similar to Arena.
 - [x] Basic functionality
 - [x] Special cases for odd layouts

### CODE REVIEW

**Comment by tooomm** [comment]
Everything stays readable and is well visible in good quality. I also like that several sides of DFC's are shown next to each other now - Meld and Fuse/Split works nicely a well! 👍
dfc
Cards in columns close to the edge of your display are also fully visibly now, unlike the old zoom where half of the card would be outside of the visible area.
I think this fully fixes https://github.com/Senryoku/MTGADraft/issues/164.

Tested on Firefox 88

I like the fade in and vanish animations a lot, too.
The size is kinda big, but ok-ish for single cards - when looking at DFC's etc. it takes up too much space though. Maybe there is a better compromise.

Ideas for improvement:
- Decrease size a bit
- A bit too much in the middle maybe (decrease gab from the sides and place more to the top or bottom?)
- Flip does not work correctly (I could rotate the small one but the big one showed default mode - I expected it to show both versions next to each other):
flip
- Aftermath also not ideal (might be a bit tricky):
aftermath

<br>

- Issues on smaller resolutions (e.g. 1376 x 768)
While both sides of DFC's are displayed completely (because smaller), normal cards are cut off on the bottom and ones containing more text are not fully readable:
small
small2

**Comment by Senryoku** [comment]
Thanks for the feedback!
 - I'll try that.
 - Will try that too, but will keep it centered vertically.
 - I wasn't sure what to do about flip cards, but yeah, I'll just display both face side by side.
 - I don't have a good solution for Aftermath, this will have to do ^^
 - Eh, weird, thought I had tested that thoroughly, will try to fix that.

**Comment by tooomm** [comment]
>- Aftermath also not ideal (might be a bit tricky):
aftermath
>     * I don't have a good solution for Aftermath, this will have to do ^^

Yeah I know, they are special indeed. :D
You could display the non-rotated card on the left of the rotated+zoomed one to allow to easily read both at the same time at least in case the popup covers the original card. If they keep the same hight it could look good still, kinda wide though (and without that much zoom - but those cards have bigger text in general). Overlaying them might look weird.

**Comment by tooomm** [comment]
In general, it looks like if cards are displayed horizontally (split, fuse, aftermath), they take up roughly the same hight as a normal, vertical one - but double the width to keep their aspect ratio, with even bigger text as they have no reminder text afaik:
normalcard
normalcard_rotated (split)
They probably need not as much zoom as they are not flooded with text. They take basically the same space as two full sides of a DFC card with potentially a lot (and smaller) text:
dfc2
(They take up even more space than a DFC 🙈)

**Comment by Senryoku** [comment]
I think I addressed most of your feedback, arguably double cards still take a lot of space, but I think it's fine as is.

**Pull request merged**
