### PR TITLE
Card pool layout

### PR DESCRIPTION
**Pull request by Senryoku**
WIP
Will use this branch to work on #145, #157, #165
(And maybe #74 simply by adding a way to remove basics)

### CODE REVIEW

**Comment by Senryoku** [comment]
@wrmacrae @tooomm Any thoughts on these changes? (Checkout the layout menu in the deployed test app)

**Comment by wrmacrae** [comment]
Ooo, this looks great! I think it's hard to predict how well users will take to it, but would recommend getting it out there and then observing usage and maybe gathering some feedback, personally I'd find this to be an improvement. I like how the labels pick up on things as appropriate but then kind of drop off gracefully when those aren't true anymore. And I imagine folks that like just moving cards around in arbitrary piles will enjoy the extra real estate even if they're not specifically using the creature/non-creature distinction.

**Comment by tooomm** [comment]
Ha, you tackled several things at once here and came up with some nice solutions. I like it.
While I followed this and played already around with it, I did not finish my review yesterday. Will open a new issue instead with my minor notes as this is merged already. 👍 

Happy to see it out there and looking forward to the user feedback!

**Comment by Senryoku** [comment]
> While I followed this and played already around with it, I did not finish my review yesterday. Will open a new issue instead with my minor notes as this is merged already. 👍

Sorry about that! I wanted to have these changes tested asap to hopefully be stable when Kaldheim drops :)

**Comment by tooomm** [comment]
Nothing to be worried about. :)

I'm looking forward to Kaldheim - maybe I get around to draft more then again as well!

**Pull request merged**
